### 여정 작성 여러개
POST http://localhost:8080/itinerary/1
Content-Type: application/json

[
  {
    "itineraryName": "부산 여정",
    "timeSchedule": {
      "startTime": "2023-10-28T13:05:00",
      "endTime": "2023-10-28T11:15:00"
    },
    "accommodation": [
      {
        "accommodationName": "신라 스테이 해운대",
        "accommodationTimeSchedule": {
          "startTime": "2023-10-27T15:00:00",
          "endTime": "2023-10-28T18:00:00"
        }
      }
    ],
    "residence": [
      {
        "residenceName": "부산",
        "residenceTimeSchedule": {
          "startTime": "2023-10-27T15:00:00",
          "endTime": "2023-10-28T18:00:00"
        }
      }
    ],
    "activity": [
      {
        "transportEnum": "KTX",
        "departurePlace": "집",
        "arrivalPlace": "부산역",
        "description": "KTX타고 드디어 부산입성!",
        "activityTimeSchedule": {
          "startTime": "2023-01-02T14:00:00",
          "endTime": "2023-01-03T11:00:00"
        }
      },
      {
        "transportEnum": "CAR",
        "departurePlace": "부산역",
        "arrivalPlace": "해운대 블루라인파크",
        "description": "스카이캡슐 타서 경치보기",
        "activityTimeSchedule": {
          "startTime": "2023-10-27T13:20:00",
          "endTime": "2023-10-27T14:00:00"
        }
      },
      {
        "transportEnum": "CAR",
        "departurePlace": "해운대 블루라인파크",
        "arrivalPlace": "개미집국제시장본점",
        "description": "부산명물 낙곱새 먹기",
        "activityTimeSchedule": {
          "startTime": "2023-10-27T14:10:00",
          "endTime": "2023-10-27T14:30:00"
        }
      },
      {
        "transportEnum": "CAR",
        "departurePlace": "개미집국제시장본점",
        "arrivalPlace": "자갈치시장",
        "description": "시장구경하고 회 포장",
        "activityTimeSchedule": {
          "startTime": "2023-10-27T14:40:00",
          "endTime": "2023-10-27T15:20:00"
        }
      },
      {
        "transportEnum": "CAR",
        "departurePlace": "자갈치시장",
        "arrivalPlace": "신라스테이해운대",
        "description": "숙소에서 저녁먹고 푹 쉬기",
        "activityTimeSchedule": {
          "startTime": "2023-10-27T17:00:00",
          "endTime": "2023-10-27T18:00:00"
        }
      },
      {
        "transportEnum": "CAR",
        "departurePlace": "신라스테이해운대",
        "arrivalPlace": "부산역",
        "description": "굿바이 부산",
        "activityTimeSchedule": {
          "startTime": "2023-10-28T10:30:00",
          "endTime": "2023-10-28T11:15:00"
        }
      },
      {
        "transportEnum": "KTX",
        "departurePlace": "부산역",
        "arrivalPlace": "집",
        "description": "집으로",
        "activityTimeSchedule": {
          "startTime": "2023-10-28T12:00:00",
          "endTime": "2023-10-28T15:00:00"
        }
      }
    ]
  }
]







