### 여정 작성 여러개
POST http://localhost:8080/itinerary/1
Content-Type: application/json

[
  {
    "itineraryName": "Seoul Itinerary",
    "timeSchedule": {
      "startTime": "2023-02-01T00:00:00",
      "endTime": "2023-02-10T00:00:00"
    },
    "accommodation": [
      {
        "accommodationName": "Lotte Hotel",
        "accommodationTimeSchedule": {
          "startTime": "2023-01-01T14:00:00",
          "endTime": "2023-01-02T11:00:00"
        }
      },
      {
        "accommodationName": "Shilla Hotel",
        "accommodationTimeSchedule": {
          "startTime": "2023-01-02T14:00:00",
          "endTime": "2023-01-03T11:00:00"
        }
      }
    ],
    "residence": [
      {
        "residenceName": "Seoul",
        "residenceTimeSchedule": {
          "startTime": "2023-01-01T00:00:00",
          "endTime": "2023-01-03T23:59:59"
        }
      }
    ],
    "transport": [
      {
        "transportEnum": "PLANE",
        "departurePlace": "Tokyo",
        "arrivalPlace": "Seoul",
        "transportTimeSchedule": {
          "startTime": "2022-12-31T20:00:00",
          "endTime": "2022-12-31T23:00:00"
        }
      },
      {
        "transportEnum": "PLANE",
        "departurePlace": "Seoul",
        "arrivalPlace": "Tokyo",
        "transportTimeSchedule": {
          "startTime": "2023-01-04T09:00:00",
          "endTime": "2023-01-04T12:00:00"
        }
      }
    ]
  }
]






