### 여행 수정
PATCH http://localhost:8080/trip/1
Content-Type: application/json

{
  "tripName": "부산 여행 일정 수정",
  "timeSchedule": {
    "startTime": "2023-02-01T00:00:00",
    "endTime": "2023-02-10T00:00:00"
  },
  "tripDestinationEnum": "DOMESTIC"
}
