spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true

  data:
    redis:
      host: travel-redis
      port: 6379
